### ISSUE TITLE
mrtpipelines.smk

### ISSUE THREAD

**Issue by kaitj** [kaitj/dbsc#4]
Reorganize this part of the workflow. Can be broken down into 3 separate phases (groups):

### Breakdown:

participant1 (phase1):
 - Perform processing up to computing average response function
 
group (phase2):
- Compute average response function

participant2 (phase3):
- Processing (including tractography) using the average response function

Most of the notes within the code that has `TODO` would be nice to have for a v0.2.x 

### TODO:

- [x] Check for any needed updates for new `snakebids` version
- [x] Add group directive to rules
- [ ] Fix the loop to update and extract individual connections
  - [ ] Optionally save 3D (.tck) files of connections 

Can look at preproc pipeline used for @mtayl84's [workflow](https://github.com/kaitj/mrtproc).
